# Generated by Django 3.2.9 on 2021-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_auto_20211129_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
