# Generated by Django 3.2.9 on 2021-11-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0005_auto_20211129_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentId',
            new_name='id',
        ),
    ]
