# Generated by Django 3.2.9 on 2021-11-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0006_rename_commentid_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backenddata',
            name='comments',
        ),
    ]
