# Generated by Django 3.2.9 on 2021-11-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0007_remove_backenddata_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='backenddata',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.comment'),
        ),
    ]
