# Generated by Django 3.2.9 on 2021-11-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0009_auto_20211129_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
