# Generated by Django 3.2.9 on 2021-11-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0010_rename_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentId',
        ),
    ]
