# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0012_alter_comments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
