# Generated by Django 3.2.9 on 2021-12-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0016_auto_20211130_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backenddata',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='videoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube_app.backenddata'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
