# Generated by Django 3.2.9 on 2021-12-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0017_auto_20211130_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='videoId',
            new_name='backendData',
        ),
    ]
