# Generated by Django 3.2.9 on 2021-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0019_auto_20211130_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddata',
            name='comments',
            field=models.ManyToManyField(blank=True, to='youtube_app.Comment'),
        ),
    ]
